accounts:
  - name: aaaa-account
    region: us-east-1
    accessKey: aaaaaaaaaaaaa
    secretKey: aaaaaaaaaaaaaaaaaaaaaaaaa
  - name: bbbbb-account
    region: us-east-1
    accessKey: bbbbbbbbbbbbb
    secretKey: bbbbbbbbbbbbbbbbbbbbbbbbb

